project:
  type: book
  output-dir: docs

book:
  title: "cbu styleguide"
  author: "Michał Wypych"
  date: "13.02.2025"
  chapters:
    - index.qmd
    - intro.qmd
    - text.qmd
    - color.qmd
    - theme.qmd
    - chart_types.qmd
    - tutorial.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

