project:
  type: book

book:
  title: "cbu styleguide"
  author: "Michał Wypych"
  date: "13.02.2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

