This part discusses specific types of charts, when to use them and some tweaks to make them work.

## General rules?

## Chart types

Ok, on to the chart types!

### Bar charts

Preferably for displaying

-   general rules

-   position dodge

-   text above

-   error bars

-   long labels:

    -   opt for coord_flip?

    -   wrap the labels

-   Likert scale issues:

    -   starting from 1: geom_col() will start from 0 by default. Override with coord_cartesian()

### Filled bar charts

-   mainly for displaying percentages

-   working with text

-   What to do with very small categories

    -   ggrepel

    -   collapse categories

    -   maybe facet_zoom?

### Line charts

-   showing changes in time

-   Avoid spaghetti plots

-   highlighting categories?

### Scatterplots

-   dealing with overplotting

-   Too many points -\> go for geom_count?

-   remember about reference line - geom_point will happily start the y axis from a number different from 0 or 1

### Line-of-best-fit charts

This in general refers to plots that show some kind of regression-like line of best fit, be it from a GLM, LOESS, GAM etc.

-   Make sure a proper interpretation is provided.

-   Try to include uncertainty

### Correlation plots?

-   right now we make bar plots. Is this the best option?

-   Do we want to include asterikses for significant relations?

### Dumbbell charts

-   showing changes

### Waffle charts?

-   do we want them? For displaying simple percentages they might be ok

### Maps?

### Pie charts

just no. Make a bar chart.

### Showing statistical models

-   SEM models?